name: CI
on:
  push:
    branches:
      - master
      - release
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge,bioconda
        channel-priority: true
        activate-environment: test
    - run: conda info
    - run: conda list
    - run: mamba install mafft raxml fasttree iqtree vcftools pip
    - run: pip install -e .[dev]
